git update-index --assume-unchanged "Minecraft Origin/hmcl.json"
git update-index --assume-unchanged "Minecraft Origin/.minecraft/config/InvTweaks.cfg"
git update-index --assume-unchanged "Minecraft Origin/.minecraft/config/randomtweaks/data.json"
git update-index --assume-unchanged "Minecraft Origin/.minecraft/liteconfig/common/autofish.json"
git update-index --assume-unchanged "Minecraft Origin/.minecraft/mods/VoxelMods/voxelmap.properties"